behaviors:
  Character:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500
    time_horizon: 64
    summary_freq: 1  # Reduced to get more frequent updates
environment_parameters:
  # Curriculum learning parameters can be added here if needed
checkpoint_settings:
  run_id: MyTrainingRun  # Changed to match command line parameter
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: true
  inference: false
torch_settings:
  device: cuda:0
debug: false