behaviors:
  # Replace MyBehavior with the name of your behavior
  Character:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000

environment_parameters:
  # You can define curriculum learning parameters here if needed
  # Example:
  # difficulty:
  #   curriculum:
  #     - name: Lesson0
  #       completion_criteria:
  #         measure: reward
  #         behavior: MyBehavior
  #         min_lesson_length: 100
  #         threshold: 0.1
  #       value: 0.0
  #     - name: Lesson1
  #       completion_criteria:
  #         measure: reward
  #         behavior: MyBehavior
  #         min_lesson_length: 100
  #         threshold: 0.3
  #       value: 0.2
  #     - name: Lesson2
  #       value: 1.0

checkpoint_settings:
  run_id: MyTrainingRun
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false

torch_settings:
  device: cuda:0  # Set to 'cuda:0' to use GPU or 'cpu' for CPU training

debug: false