const fs = require('fs');

function art(data) {
    return {
        artifactName: data.name,
        hidden: true,
        alignment: data.align,
        transferable: true,
        spriteString: data.sprite || "artifact",
        commanderBonus: data.cmd || 0,
        agentBonus: data.agent || 0,
        emmissaryBonus: data.em || 0,
        mageBonus: data.mage || 0,
        bonusAttack: data.atk || 0,
        bonusDefense: data.def || 0,
        healPerTurn: data.heal || 0,
        movementBonus: data.move || 0,
        ignoreTerrainMovementPenalty: data.ignoreTerrain || false,
        grantsHasteAtSea: data.hasteSea || false,
        autoScoutRadius: data.scout || 0,
        detectionEvasion: data.evasion || 0,
        attackBonusVsRace: data.atkRace || "",
        attackBonusVsRaceValue: data.atkRaceVal || 0,
        attackBonusVsTroopType: data.atkTroop || "",
        attackBonusVsTroopTypeValue: data.atkTroopVal || 0,
        defenseBonusVsRace: data.defRace || "",
        defenseBonusVsRaceValue: data.defRaceVal || 0,
        defenseBonusVsTroopType: data.defTroop || "",
        defenseBonusVsTroopTypeValue: data.defTroopVal || 0,
        armyAttackStrengthBonus: data.armyAtk || 0,
        armyDefenseStrengthBonus: data.armyDef || 0,
        enemyArmyDefensePenaltySameHex: data.enemyDefPen || 0,
        recruitBonusMenAtArms: data.recruitMA || 0,
        scryAreaBonus: data.scryArea || 0,
        scryArtifactBonus: data.scryArt || 0,
        negativeStatusImmunity: data.immune || "",
        negativeStatusDurationReduction: data.negDurRed || 0,
        negativeStatusDamageReduction: data.negDmgRed || 0,
        positiveStatusDurationBonus: data.posDurBon || 0,
        positiveStatusEffectBonus: data.posEffBon || 0,
        grantsEnvironmentalImmunity: data.envImmune || false,
        passiveEffectId: data.legacyId || "",
        passiveEffectValue: data.legacyVal || 0
    };
}

// align: 0=neutral, 1=dark, 2=free
const artifacts = [
    // Dark (1)
    art({ name: "Goblin Cleaver", align: 1, sprite: "scimitar", atk: 1, atkRace: "Orc", atkRaceVal: 1 }),
    art({ name: "River Lillies", align: 2, sprite: "lillies", mage: 1, heal: 1, posDurBon: 1 }),
    art({ name: "Oak Shield", align: 2, sprite: "timber", def: 1, defRace: "Orc", defRaceVal: 1 }),
    art({ name: "Ring of Wind", align: 2, sprite: "ring", agent: 1, move: 1 }),
    art({ name: "Tinculin", align: 0, sprite: "ring", mage: 1, scryArea: 1 }),
    art({ name: "Staff of Storms", align: 2, sprite: "staff", mage: 1, hasteSea: true }),
    art({ name: "Palantir of Annuminas", align: 2, sprite: "palantir", mage: 1, scout: 1, scryArea: 2, scryArt: 10 }),
    art({ name: "Palantir of Amon Sul", align: 2, sprite: "palantir", agent: 1, scout: 1, scryArea: 2, scryArt: 10 }),
    art({ name: "Helm of Isildur", align: 0, sprite: "helm", cmd: 1, def: 1 }),
    art({ name: "Durin's Armour", align: 0, sprite: "helm", def: 1, defRace: "Orc", defRaceVal: 1 }),
    art({ name: "Elfbane", align: 1, sprite: "scimitar", atk: 1, def: 1, atkRace: "Elf", atkRaceVal: 1 }),
    art({ name: "Elfbane", align: 1, sprite: "scimitar", atk: 1, def: 1, atkRace: "Elf", atkRaceVal: 1 }),
    art({ name: "Durin's Axe", align: 0, sprite: "axe", cmd: 1, atk: 1, atkRace: "Orc", atkRaceVal: 1, defRace: "Orc", defRaceVal: 1 }),
    art({ name: "Orcring", align: 1, sprite: "scimitar", cmd: 1, atkRace: "Common", atkRaceVal: 1 }),
    art({ name: "Troll Cleaver", align: 1, sprite: "long_axe", atk: 1, atkRace: "Troll", atkRaceVal: 1 }),
    art({ name: "Horse-tamer", align: 0, sprite: "staff", cmd: 1, atkTroop: "hc", atkTroopVal: 1, recruitMA: 1 }),
    art({ name: "Staff of the Wanderer", align: 2, sprite: "staff", agent: 1, move: 1 }),
    art({ name: "The Blue Ring", align: 0, sprite: "ring", mage: 1, def: 1, defRace: "Orc", defRaceVal: 1, evasion: 1 }),
    art({ name: "Red Robes", align: 2, sprite: "cloak", mage: 1, posDurBon: 1 }),
    art({ name: "Mantle of Doriath", align: 0, sprite: "mantle", def: 1, evasion: 2 }),
    art({ name: "Voice of the Dark Tower", align: 1, sprite: "leather", em: 1, evasion: 1, immune: "Fear" }),
    art({ name: "Usriev", align: 1, sprite: "scythe", atk: 1, atkTroop: "hi", atkTroopVal: 1, armyAtk: 1 }),
    art({ name: "Cloak of Duvorn", align: 1, sprite: "cape", em: 2, evasion: 1, immune: "Despair" }),
    art({ name: "Storm dagger", align: 1, sprite: "dagger", mage: 1, atk: 1, atkRace: "Elf", atkRaceVal: 1 }),
    art({ name: "Bracers of the Mist", align: 2, sprite: "bracers", agent: 1, def: 1, evasion: 1, immune: "Poisoned" }),
    art({ name: "Athelas", align: 0, sprite: "herb", mage: 1, heal: 1, immune: "Poisoned", negDmgRed: 1 }),
    art({ name: "Athelas", align: 0, sprite: "herb", mage: 1, heal: 1, immune: "Poisoned", negDmgRed: 1 }),
    art({ name: "Athelas", align: 0, sprite: "herb", mage: 1, heal: 1, immune: "Poisoned", negDmgRed: 1 }),
    art({ name: "Athelas", align: 0, sprite: "herb", mage: 1, heal: 1, immune: "Poisoned", negDmgRed: 1 }),
    art({ name: "Athelas", align: 0, sprite: "herb", mage: 1, heal: 1, immune: "Poisoned", negDmgRed: 1 }),
    art({ name: "Ovir Crown", align: 2, sprite: "crown", cmd: 1, def: 1 }),
    art({ name: "Listening Helm", align: 2, sprite: "crown", agent: 1, scout: 1, scryArea: 1 }),
    art({ name: "Ghostbane", align: 1, sprite: "scythe", atk: 1, def: 1, atkRace: "Undead", atkRaceVal: 1, defRace: "Undead", defRaceVal: 1 }),
    art({ name: "Horn of Fear", align: 1, sprite: "horn", atk: 1, atkTroop: "li", atkTroopVal: 1, enemyDefPen: 1 }),
    art({ name: "Dawnsword", align: 1, sprite: "scimitar", atk: 1, envImmune: true }),
    art({ name: "Staff of Light", align: 0, sprite: "ring", mage: 1, posDurBon: 1 }),
    art({ name: "Fireworks", align: 0, sprite: "fireworks", em: 1, posDurBon: 1 }),
    art({ name: "The Black Book", align: 1, sprite: "book", mage: 1, atk: 1, atkRace: "Elf", atkRaceVal: 1, evasion: 1, immune: "Despair" }),
    art({ name: "Trap", align: 2, sprite: "rope", def: 1, defTroop: "li", defTroopVal: 1, armyDef: 1 }),
    art({ name: "Elven Rope", align: 0, sprite: "rope", agent: 1, move: 1, ignoreTerrain: true }),
    art({ name: "Wine", align: 2, sprite: "wine", em: 1, negDurRed: 1 }),
    art({ name: "Liquour", align: 2, sprite: "wine", em: 1, immune: "Fear" }),
    art({ name: "Song", align: 0, sprite: "scroll", em: 1, atk: 1, atkRace: "Orc", atkRaceVal: 1 }),
    art({ name: "Red Book of Westmarch", align: 0, sprite: "book", cmd: 1, posDurBon: 1 }),
    art({ name: "Book of Kings", align: 0, sprite: "book", em: 1, def: 1, defRace: "Orc", defRaceVal: 1 }),
    art({ name: "Book of Mazarbul", align: 0, sprite: "book", cmd: 1, atk: 1, atkRace: "Goblin", atkRaceVal: 1 }),
    art({ name: "Dwarven Key", align: 0, sprite: "key", agent: 1, scryArt: 10 }),
    art({ name: "Ithildin Runes", align: 0, sprite: "map", mage: 1, scryArea: 1, scryArt: 5 }),
    art({ name: "Ring of Binding", align: 2, sprite: "ring", agent: 1, atk: 1, atkRace: "Orc", atkRaceVal: 1, evasion: 1 }),
    art({ name: "Second Age Banner", align: 0, sprite: "book", cmd: 1, atkTroop: "hc", atkTroopVal: 1, armyAtk: 1 }),
    art({ name: "First Age Banner", align: 0, sprite: "book", cmd: 1, defTroop: "lc", defTroopVal: 1, armyDef: 1 }),
    art({ name: "Staff of Fire", align: 2, sprite: "staff", mage: 1, immune: "Burning" }),
    art({ name: "Black Powder", align: 2, sprite: "powder", atk: 1, atkTroop: "ca", atkTroopVal: 1 }),
    art({ name: "Dorwinion Tobacco", align: 2, sprite: "tobacco", agent: 1, posDurBon: 1 }),
    art({ name: "Old Tobby", align: 2, sprite: "tobacco", cmd: 1, posDurBon: 1 }),
    art({ name: "Staff of Secret Fire", align: 0, sprite: "staff", mage: 1, immune: "Burning" }),
    art({ name: "Star Powder", align: 0, sprite: "powder", mage: 1, posDurBon: 1 }),
    art({ name: "Andúril", align: 2, sprite: "sword", cmd: 1, atk: 1, atkRace: "Orc", atkRaceVal: 1, posDurBon: 1 }),
    art({ name: "Black Arrow", align: 0, sprite: "bow", atk: 1, atkRace: "Dragon", atkRaceVal: 1 }),
    art({ name: "The Arkenstone", align: 2, sprite: "gems", em: 1, cmd: 1, def: 1, defRace: "Orc", defRaceVal: 1 }),
    art({ name: "Mathom", align: 2, sprite: "artifact", em: 1, recruitMA: 1 }),
    art({ name: "Crown of Cardolan", align: 2, sprite: "jewel", cmd: 1, defRace: "Orc", defRaceVal: 1, armyAtk: 1 }),
    art({ name: "TheMirrorOfGaladriel", align: 0, sprite: "palantir", mage: 1, scout: 1, scryArea: 2, scryArt: 10 }),
    art({ name: "Cardolan Seal", align: 2, sprite: "jewel", agent: 1, scryArt: 15 }),
    art({ name: "Seal of Dawn", align: 2, sprite: "jewel", cmd: 1, heal: 1, immune: "Despair", negDurRed: 1 }),
];

const output = { artifacts };
fs.writeFileSync('Assets/Resources/Artifacts.json', JSON.stringify(output, null, 4));
console.log('Wrote', artifacts.length, 'artifacts');
