public enum CardSituationEnum
{
    None = 0,
    ArmyAtEnemyPC = 1,
    AgentAtEnemyPC = 2,
    EmmissaryAtEnemyPC = 3,
    ArmyAtFriendlyPC = 4,
    EmmissaryAtOwnPC = 5,
    AgentAtOwnPC = 6,
    ArmyAtHexWithEnemyArmyAndNoPC = 7,
    AgentAtHexWithEnemyCharacter = 8,
    EmmissaryAtHexWithEnemyCharacter = 9,
    MageAtHexWithEnemyCharacter = 10,
    MageAtArtifactHex = 11,
    CommanderAtOwnPC = 12,
    EmmissaryAtFriendlyPC = 13,
    AgentWithHostage = 14,
    ArmyAtEnemyPCorEnemyArmy = 15,
    EnemyAgentWithMyHostageAtHex = 16,
    OwnDoubledCharacterByEnemyAtHex = 17,
    EnemyCharacterAtHex = 18,
    EnemyCharacterAtHexNoArmyCommander = 19,
    EnemyMageAtHex = 20,
    FriendlyCharacterAtHex = 21
}
